### ISSUE TITLE
Refactor of GroupCommutatorIteration not integrated with utils.py

### ISSUE THREAD

**Issue by marekgluza** [qiboteam/boostvqe#86]
https://github.com/qiboteam/boostvqe/blob/827b25fd1168a66f903c1820a4892da4d0121d57/src/boostvqe/utils.py#L251-L254

the loading of VQE is now left hanging (e.g. github doesn't find the definition)

**Comment by andrea-pasquale** [comment]
The function `initialize_gci_from_vqe` is probably outdated at this point since we are no longer using it in `main.py`. Either we update it or we should explicitly put somewhere how to load a trained model.
