### ISSUE TITLE
Clean up branches

### ISSUE THREAD

**Issue by marekgluza** [qiboteam/boostvqe#89]
We have too many branches with unclear names.

- [ ] can I remove the merged branches?
- [ ] can you check which of your branches are active code dev and remove those that are discontinued?

**Comment by andrea-pasquale** [comment]
> * can I remove the merged branches?

Yes, @marekgluza feel free to remove them.

We only need to be careful about branches which are not associated to a PR that we want keep like the one where we are implenting boostvqe for quantinuum
